---
kind: pipeline
type: docker
name: java-pipeline

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  - name: test
    image: youngphoenix09/cibox:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
     - ./setuplocal.sh
     - ./gradlew test
#  - name: comment-pr
#    image: maniator/gh
#    commands:
#      - gh issue {pr#} comment --body "@dependabot squash and merge"
#    environment:
#      GH_TOKEN:
#        from_secret: gh_token
