---
kind: pipeline
type: docker
name: java-pipeline

steps:
  - name: test
    image: cibox
    commands:
      - gradle wrapper
      - ./setuplocal.sh
      - ./gradlew test
#  - name: comment-pr
#    image: maniator/gh
#    commands:
#      - gh issue {pr#} comment --body "@dependabot squash and merge"
#    environment:
#      GH_TOKEN:
#        from_secret: gh_token
