version: '2.4'
services:
  database:
    #    image: postgres
    image: postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - database.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 0.5s
      timeout: 25s
      retries: 25
